name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm install

      - name: Grant execute permissions for wdio
        run: chmod +x ./node_modules/.bin/wdio

      - name: Run tests
        run: npm run wdio
